# Generated by Django 3.0.8 on 2021-09-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_validation', '0002_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokens',
            options={'permissions': (('can_bulk_uploaded', 'Can bulk uploaded token CSV'),), 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
